apiVersion: v1
kind: Service
metadata:
  name: Ramana-backend-service
  namespace: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
