apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: venkat345/my-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: VITE_BACKEND_URL
